### ISSUE TITLE
Get Shit Done

### ISSUE THREAD

**Issue by NikhilPeri** [uorocketry/barista#48]
- [x] wire up board
- [x] `read_acceleration` and `read_orientation` returns a hash
- [x] client to send and receive radio
- [x] revisit airbrakes and make sure they work
- [x] Implement altimeter
- [x] Test altimeter
- [ ] Add Tests for IMU
- [ ] Implement brake deploy algorithm
- [ ] take orientation on initialization
- [x] power on and test COTS altimeter
- [x] range test radios

**Comment by buzuloiu** [comment]
- [ ] tare orientation on initialization

**Comment by buzuloiu** [comment]
Things that may or may not be done, but need to be 
feel free to add anything I missed

# hardware

## sensors
- [x] solder GPS wires
- [x] solder IMU wires
- [x] solder altimeter wires
- [ ] solder buzzer terminal blocks
- [ ] solder buzzer gpio

## physical assembly
- [ ] bondo electronics cards
- [ ] put sensors on card

# software
- [ ] test altimeter code
- [ ] interpret GPS data correctly to see if there is a parsing issue
- [ ] test buzzer code
- [ ] add buzzer to each rocket state

**Comment by NikhilPeri** [comment]
I geuss we can call this shit done!

#mission-accomplished
